taxonomy_mismatches <- c(
  "Anthoxanthum alpinum Á. Löve & D. Löve",
  "Anthoxanthum alpinum Á. Löve & D. Löve",
  "Alchemilla glabra Neygenf.",
  "Phleum rhaeticum (Humphries) Rauschert",
  "Juniperus communis subsp. alpina Celak.",
  "Juniperus communis subsp. alpina Celak.",
  "Ranunculus tuberosus Lapeyr.",
  "Ranunculus tuberosus Lapeyr.",
  "Alchemilla decumbens Buser",
  "Poa supina Schrad.",
  "Alnus viridis (Chaix) DC.",
  "Alnus viridis (Chaix) DC.",
  "Alnus viridis (Chaix) DC.",
  "Dryopteris dilatata (Hoffm.) A. Gray",
  "Silene exscapa All.",
  "Silene exscapa All.",
  "Diphasiastrum alpinum (L.) Holub",
  "Euphrasia rostkoviana subsp. montana (Jord.) We...",
  "Euphrasia rostkoviana subsp. montana (Jord.) We...",
  "Euphrasia rostkoviana subsp. montana (Jord.) We...",
  "Brachypodium rupestre (Host) Roem. & Schult.",
  "Brachypodium rupestre (Host) Roem. & Schult.",
  "Brachypodium rupestre (Host) Roem. & Schult.",
  "Molinia arundinacea Schrank",
  "Galium lucidum All.",
  "Agrostis gigantea Roth",
  "Phyteuma betonicifolium Vill.",
  "Lamium galeobdolon (L.) L.",
  "Lamium galeobdolon (L.) L. subsp. galeobdolon",
  "Lamium galeobdolon subsp. argentatum (Smejkal) J. Duvign.",
  "Lamium galeobdolon subsp. flavidum (F. Herm.) Á. Löve & D. Löve",
  "Lamium galeobdolon subsp. montanum (Pers.) Hayek",
  "Sesleria caerulea (L.) Ard.",
  "Gentiana clusii E. P. Perrier & Songeon",
  "Dryopteris affinis (Lowe) Fraser-Jenk.",
  "Carex spicata Huds.",
  "Myosotis decumbens Host",
  "Chaerophyllum villarsii W. D. J. Koch",
  "Cystopteris alpina (Lam.) Desv.",
  "Dactylorhiza lapponica (Laest. ex Hartm.) Soó",
  "Dactylorhiza lapponica (Laest. ex Hartm.) Soó",
  "Dactylorhiza lapponica (Laest. ex Hartm.) Soó",
  "Dactylorhiza lapponica (Laest. ex Hartm.) Soó",
  "Carex lepidocarpa Tausch",
  "Rhinanthus glacialis Personnat",
  "Leucanthemum adustum (W. D. J. Koch) Gremli",
  "Crepis kerneri Rech. f.",
  "Crepis kerneri Rech. f.",
  "Crepis kerneri Rech. f.",
  "Campanula scheuchzeri Vill.",
  "Galium pumilum Murray",
  "Myosotis alpestris F. W. Schmidt",
  "Dryopteris dilatata (Hoffm.) A. Gray",
  "Senecio ovatus (G. Gaertn., B. Mey. & Scherb.) Hoppe",
  "Elymus hispidus (Opiz) Melderis",
  "Elymus hispidus (Opiz) Melderis",
  "Elymus hispidus (Opiz) Melderis",
  "Sedum montanum Songeon & E. P. Perrier",
  "Sedum montanum Songeon & E. P. Perrier",
  "Scabiosa lucida Vill.",
  "Lotus alpinus (DC.) Ramond",
  "Lotus alpinus (DC.) Ramond",
  "Molinia arundinacea Schrank",
  "Carex parviflora Host",
  "Alchemilla nitida Buser",
  "Festuca quadriflora Honck.",
  "Festuca quadriflora Honck.",
  "Bromus benekenii (Lange) Trimen",
  "Pseudolysimachion spicatum (L.) Opiz",
  "Conyza sumatrensis (Retz.) E. H. Walker",
  "Sedum telephium L.",
  "Sedum telephium L.",
  "Dianthus carthusianorum L.",
  "Hieracium murorum aggr.",
  "Ranunculus trichophyllus Chaix",
  "Plantago alpina L.",
  "Senecio ovatus (G. Gaertn. & al.) Willd.",
  "Arabis subcoriacea Gren.",
  "Arabis subcoriacea Gren."
  )

alternative_names <- c(
  # A. alpinum = subsp. of odoratum according to POWO; F.Inc. makes both an agg
  "Anthoxanthum odoratum",
  "Anthoxanthum odoratum agg.",
  NA,
  NA,
  # Juniperus communis subsp. alpina Celak only in Swiss checklist
  "Juniperus communis subsp. alpina (Suter) Celak.",
  "Juniperus communis var. saxatilis Pall.",
  # Flora Incognita: Ranunculus tuberosus Lapeyr. = R. polynthemos subsp. nemor.
  "Ranunculus polyanthemos subsp. nemorosus (DC.) Schübl. & G. Martens",
  "Ranunculus polyanthemos",
  NA,
  NA,
  "Alnus alnobetula subsp. alnobetula",
  "Alnus alnobetula (Ehrh.) K.Koch",
  "Alnus alnobetula",
  NA,
  "Silene acaulis subsp. bryoides",
  "Silene acaulis",
  NA,
  "Euphrasia officinalis subsp. pratensis Fr.",
  "Euphrasia officinalis",
  NA,
  NA,
  "Brachypodium pinnatum (L.) P.Beauv.",
  "Brachypodium pinnatum",
  NA,
  NA,
  NA,
  NA,
  NA,
  NA,
  NA,
  NA,
  NA,
  NA,
  NA,
  NA,
  NA,
  NA,
  NA,
  NA,
  NA,
  "Dactylorhiza majalis subsp. lapponica (Laest. ex Hartm.) H.Sund.",
  "Dactylorhiza majalis",
  "Dactylorhiza majalis (Rchb.) P.F.Hunt & Summerh.",
  NA,
  NA,
  NA,
  "Crepis jacquinii subsp. kerneri (Rech. f.) Merxm.",
  "Crepis jacquinii",
  "Crepis jacquinii Tausch",
  NA,
  NA,
  NA,
  NA,
  NA,
  "Thinopyrum intermedium subsp. intermedium",
  "Thinopyrum intermedium",
  "Elytrigia intermedia (Host) Nevski",
  "Sedum montanum Song. & Perr.",
  NA,
  NA,
  "Lotus alpinus (Schleich. ex DC.) Ramond",
  NA,
  NA,
  NA,
  NA,
  "Festuca pumila Chaix",
  "Festuca pumila",
  NA,
  NA,
  "Erigeron sumatrensis Retz.",
  NA,
  "Hylotelephium telephium (L.) H.Ohba",
  NA,
  "Crepis tectorum",
  NA,
  "Plantago maritima",
  NA,
  "Arabis soyeri Reut. & A.L.P.Huet",
  "Arabis soyeri"
  )

alternative_aggs <- c(
  NA,
  NA,
  # For Flora Incognita: A. glabra is in A. vulgaris agg.
  "Alchemilla vulgaris agg.",
  # For Flora Incognita: P. rhaethicum is in P. alpinum agg.
  "Phleum alpinum agg.",
  NA,
  NA,
  NA,
  NA,
  # For Flora Incognita: A. decumbens is in A. vulgaris agg.
  # Note: POWO recognises A. decumbens as a species
  "Alchemilla vulgaris agg.",
  # For Flora Incognita: Poa supina is in P. annua agg.
  "Poa annua agg.",
  NA,
  NA,
  NA,
  "Dryopteris carthusiana agg.",
  NA,
  NA,
  "Diphasiastrum complanatum agg.",
  NA,
  NA,
  "Euphrasia officinalis agg.",
  "Brachypodium pinnatum agg.",
  NA,
  NA,
  "Molinia caerulea agg.",
  "Galium mollugo agg.",
  "Agrostis stolonifera agg.",
  "Phyteuma michelii agg.",
  "Galeobdolon luteum agg.",
  "Galeobdolon luteum agg.",
  "Galeobdolon luteum agg.",
  "Galeobdolon luteum agg.",
  "Galeobdolon luteum agg.",
  "Sesleria varia agg.",
  "Gentiana acaulis agg.",
  "Dryopteris filix-mas agg.",
  "Carex muricata agg.",
  "Myosotis sylvatica agg.",
  "Chaerophyllum hirsutum agg.",
  "Cystopteris fragilis agg.",
  "Dactylorhiza majalis agg.",
  NA,
  NA,
  NA,
  "Carex flava agg.",
  "Rhinanthus aristatus agg.",
  "Leucanthemum vulgare agg.",
  NA,
  NA,
  NA,
  "Campanula rotundifolia agg.",
  "Galium pusillum agg.",
  "Myosotis sylvatica agg.",
  "Dryopteris carthusiana agg.",
  "Senecio nemorensis agg.",
  NA,
  NA,
  NA,
  NA,
  "Sedum rupestre agg.",
  "Scabiosa columbaria agg.",
  NA,
  "Lotus corniculatus agg.",
  "Molinia caerulea agg.",
  "Carex atrata agg.",
  "Alchemilla conjuncta agg.",
  NA,
  NA,
  "Bromus ramosus agg.",
  "Veronica spicata agg.",
  NA,
  "Hylotelephium telephium agg.",
  NA,
  "Dianthus carthusianorum agg.",
  NA,
  "Ranunculus aquatilis agg.",
  NA,
  "Senecio nemorensis agg.",
  NA,
  NA
)